account/urls.py
from django.contrib.auth import views
from django.urls import path
from django.conf.urls import include


from .views import (
    ArticleList,
    article_create_view,
    ArticleUpdate,
CustomLoginView,
CategoryCreateView,CategoryDeleteView,CategoryListView,CategoryUpdateView,
    ArticleDelete,
    delete_article_image
)

app_name = 'account'

urlpatterns = [
	path('', ArticleList.as_view(), name="home"),
    path('article/update/<int:pk>', ArticleUpdate.as_view(), name="article_update"),
    path('article/create/', article_create_view, name="article_create"),
	path('article/delete/<int:pk>', ArticleDelete.as_view(), name="article_delete"),
    path('login/', CustomLoginView.as_view(), name = 'login'),
    path('delete-article-image/<int:image_id>/', delete_article_image, name='delete-article-image'),
    path('categories/', CategoryListView.as_view(), name = 'category_list'),
    path('categories/add/', CategoryCreateView.as_view(), name = 'category_add'),
    path('categories/edit/<int:pk>/', CategoryUpdateView.as_view(), name = 'category_edit'),
    path('categories/delete/<int:pk>/', CategoryDeleteView.as_view(), name = 'category_delete'),

]

esmaeiliweb/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls',namespace='home')),
    path('accounts/', include('account.urls',namespace='account')),

]
from django.conf import settings
from django.conf.urls.static import static

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from .views import HomeView,ArticleDetail


app_name = 'home'

urlpatterns = [

    path('', HomeView.as_view(), name = 'home'),
    path('article/<int:id>', ArticleDetail.as_view(), name = "post_detail"),
]

templates/inc/messages.html
{% if messages %}
    {% for msg in messages %}
        <p class="alert alert-{{ msg.tags }}">{{ msg }}</p>
    {% endfor %}
{% endif %}

templates/inc/navbar.html
{% load static %}
<div class="container-fluid position-relative p-0 rtl">
    <nav class="navbar navbar-expand-lg navbar-light bg-white px-4 px-lg-5 py-3 py-lg-0">
        <a href="" class="navbar-brand p-0">
            <div class="row">
                <div>
                    <img src="{% static 'asset/img/logo.png' %}" alt="Logo" style="width: 100px; height: 50px;">
                </div>
            </div>
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <div class="navbar-nav d-flex justify-content-center w-100">
                <li><a class="nav-link scrollto active" href="#hero" style="font-family: Sahel; color: #0b1281;">صفحه اصلی</a></li>
                <li><a class="nav-link scrollto" href="{% url 'home:home' %}" style="font-family: Sahel; color: #0b1281;">اخبار</a></li>
                <li><a class="nav-link scrollto" href="{% url 'home:vokala' %}" style="font-family: Sahel; color: #0b1281;">جستجوی وکیل</a></li>
                <li><a class="nav-link scrollto" href="{% url 'home:karamozan' %}" style="font-family: Sahel; color: #0b1281;">جستجوی کارآموز</a></li>
                <li><a class="nav-link scrollto" href="#riyast" style="font-family: Sahel; color: #0b1281;">هیات مدیره</a></li>
                <div class="nav-item dropdown" style="font-family: Sahel; color: #0b1281;">
                    <a href="#" class="nav-link" data-bs-toggle="dropdown" style="font-family: Sahel; color: #0b1281;">
                        <span class="dropdown-toggle" style="font-family: Sahel; color: #0b1281;">کمیسیون ها</span>
                    </a>
                    <div class="dropdown-menu">
                        {% for i in comi %}
                        <a href="{% url 'home:comision_detail' i.id %}" class="dropdown-item" style="font-family: Sahel; color: #073270;">
                            {{ i.name }}
                        </a>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </nav>

    <!-- Carousel Start - Improved Version -->
    <div class="header-carousel owl-carousel position-relative">
        <!-- Item 1 -->
        <div class="header-carousel-item position-relative">
            <img src="{% static 'back.webp' %}" class="img-fluid w-100 h-100" style="object-fit: cover; min-height: 500px;" alt="Image">
            <div class="carousel-caption position-absolute top-0 start-0 w-100 h-100 d-flex align-items-center">
                <div class="container">
                    <div class="row gy-0 gx-5">
                        <div class="col-lg-0 col-xl-5"></div>
                        <div class="col-xl-7 animated fadeInLeft">
                            <div class="text-sm-center text-md-end">
                                <h4 class="text-uppercase fw-bold mb-4" style="font-family: 'B Titr'; font-size: clamp(2rem, 5vw, 55px);"></h4>
                                <div class="d-flex align-items-center justify-content-center justify-content-md-end"></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        
        <!-- Item 2 -->
{#        <div class="header-carousel-item position-relative">#}
{#            <img src="{% static 'night.webp' %}" class="img-fluid w-100 h-100" style="object-fit: cover; min-height: 500px;" alt="Image">#}
{#            <div class="carousel-caption position-absolute top-0 start-0 w-100 h-100 d-flex align-items-center">#}
{#                <div class="container">#}
{#                    <div class="row g-5">#}
{#                        <div class="col-12 animated fadeInUp">#}
{#                            <div class="text-center"></div>#}
{#                        </div>#}
{#                    </div>#}
{#                </div>#}
{#            </div>#}
{#        </div>#}
        
        <!-- Item 3 -->
        <div class="header-carousel-item position-relative">
            <img src="{% static 'ham.webp' %}" class="img-fluid w-100 h-100" style="object-fit: cover; min-height: 500px;" alt="Image">
            <div class="carousel-caption position-absolute top-0 start-0 w-100 h-100 d-flex align-items-center">
                <div class="container">
                    <div class="row g-5">
                        <div class="col-12 animated fadeInUp">
                            <div class="text-center"></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        
        <!-- Item 4 -->
        <div class="header-carousel-item position-relative">
            <img src="{% static 'licensed-image.webp' %}" class="img-fluid w-100 h-100" style="object-fit: cover; min-height: 500px;" alt="Image">
            <div class="carousel-caption position-absolute top-0 start-0 w-100 h-100 d-flex align-items-center">
                <div class="container">
                    <div class="row g-5">
                        <div class="col-12 animated fadeInUp">
                            <div class="text-center"></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Carousel End -->
</div>

<style>
    /* Custom CSS for carousel */
    .header-carousel {
        width: 100%;
    }
    
    .header-carousel-item {
        height: 90vh;
        min-height: 500px;
        max-height: 800px;
    }
    
    .carousel-caption {
        background: rgba(0, 0, 0, 0.2);
    }
    
    @media (max-width: 992px) {
        .header-carousel-item {
            height: 70vh;
        }
    }
    
    @media (max-width: 768px) {
        .header-carousel-item {
            height: 60vh;
            min-height: 400px;
        }
        
        .carousel-caption .container {
            padding-top: 40px;
            padding-bottom: 40px;
        }
    }
</style>

templates/inc/search_box.html
<!-- templates/inc/search_box.html -->
<div class="container mb-5">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <form method="GET" action="{% url 'home:search_articles' %}" class="search-form">
                <div class="input-group">
                    <input
                        type="text"
                        name="q"
                        class="form-control"
                        placeholder="جستجو در اخبار..."
                        aria-label="Search"
                        value="{{ query }}"
                    >
                    <button class="btn btn-primary" type="submit">
                        <i class="fas fa-search"></i>
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>

templates/inc/sidebar.html
{% load static %}

<aside class="main-sidebar sidebar-dark-primary elevation-4">
  <!-- Brand Logo -->
  <a href="#" class="brand-link text-center">
    <span class="brand-text" style="font-family: 'B Titr'; font-size: 14px;">حمید به گذر</span>
  </a>

  <!-- Sidebar -->
  <div class="sidebar">
    <nav class="mt-2" style="font-family: 'Sahel';">
      <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">

        <!-- اخبار -->
        <li class="nav-item has-treeview">
          <a href="#" class="nav-link active">
            <i class="nav-icon fa fa-newspaper"></i>
            <p>اخبار<i class="right fas fa-angle-left"></i></p>
          </a>
          <ul class="nav nav-treeview">
            <li class="nav-item">
              <a href="{% url 'account:home' %}" class="nav-link">
                <i class="fa fa-list nav-icon"></i>
                <p>لیست اخبار</p>
              </a>
            </li>
            <li class="nav-item">
              <a href="{% url 'account:article_create' %}" class="nav-link">
                <i class="fa fa-plus-square nav-icon"></i>
                <p>افزودن خبر</p>
              </a>
            </li>
          </ul>
        </li>
        <li class="nav-item has-treeview">
          <a href="#" class="nav-link active">
            <i class="nav-icon fa fa-newspaper"></i>
            <p>دسته بندی<i class="right fas fa-angle-left"></i></p>
          </a>
          <ul class="nav nav-treeview">
            <li class="nav-item">
              <a href="{% url 'account:category_list' %}" class="nav-link">
                <i class="fa fa-list nav-icon"></i>
                <p>لیست دسته بندی</p>
              </a>
            </li>
            <li class="nav-item">
              <a href="{% url 'account:category_add' %}" class="nav-link">
                <i class="fa fa-plus-square nav-icon"></i>
                <p>افزودن دسته بندی</p>
              </a>
            </li>
          </ul>
        </li>
{#  <li class="nav-item" style="list-style-type:none;">#}
{#                  <a href="{% url 'account:category_add' %}" class="nav-link">#}
{#                    <i class="fa fa-plus-square"></i>#}
{#                    <p>افزودن دسته بندی#}
{# </p>#}
{#                  </a>               #}
{#                </li>#}
{#                    <li class="nav-item" style="list-style-type:none;">#}
{#                  <a href="{% url 'account:category_list' %}" class="nav-link">#}
{#                    <i class="fa fa-plus-square"></i>#}
{#                    <p>لیست دسته بندی#}
{# </p>#}
{#                  </a>               #}
{#                </li>#}
{#        #}

      </ul>
    </nav>
  </div>
</aside>